### ISSUE TITLE
"Recommendations" error

### ISSUE THREAD

**Issue by rhagarty** [IBM/elasticsearch-spark-recommender#10]
All the recommendation steps at the end of the notebook had errors, all similar to the following:

NameError                                 Traceback (most recent call last)
<ipython-input-32-4124b669db7b> in <module>()
----> 1 display_user_recs(12, num=5, num_last=5)

<ipython-input-28-abb0178f3e82> in display_user_recs(the_id, q, num, num_last, index)
    103     i = 0
    104     for movie in user_movies:
--> 105         movie_im_url = get_poster_url(movie['tmdbId'])
    106         movie_title = movie['title']
    107         user_html += "<td><h5>%s</h5><img src=%s width=150></img></td>" % (movie_title, movie_im_url)

<ipython-input-28-abb0178f3e82> in get_poster_url(id)
      9         poster_url = IMAGE_URL + movie['poster_path'] if 'poster_path' in movie and movie['poster_path'] is not None else ""
     10         return poster_url
---> 11     except ModuleNotFoundError:
     12         return "NA"
     13 

NameError: global name 'ModuleNotFoundError' is not defined

NOTE - this is probably related to the fact that I did NOT do the optional step of setting up the tmdb.API_KEY (I had errors). If so, the name of the recommended movie should still be listed, even if it's poster can't be found. 

Otherwise, the optional step should probably be required.

**Comment by MLnick** [comment]
Ah - so you _did_ install `tmdbsimple` but _did not_ set the `API_KEY`?

**Comment by MLnick** [comment]
I can't reproduce this exact error.

If I _have_ installed `tmdbsimple`, but _did not_ run the "Toy Story poster test cell", and also _have not_ set the API key, I get:

```
APIKeyError                               Traceback (most recent call last)
<ipython-input-28-13f0c7366a96> in <module>()
----> 1 display_similar(2628, num=5)

<ipython-input-27-9c5a8e0290b5> in display_similar(the_id, q, num, index, dt)
    133     """
    134     movie, recs = get_similar(the_id, q, num, index, dt)
--> 135     q_im_url = get_poster_url(movie['tmdbId'])
    136     if q_im_url == "NA":
    137         display(HTML("<i>Cannot import tmdbsimple, no movie posters will be displayed!</i>"))

<ipython-input-27-9c5a8e0290b5> in get_poster_url(id)
      6     try:
      7         import tmdbsimple as tmdb
----> 8         movie = tmdb.Movies(id).info()
      9         poster_url = IMAGE_URL + movie['poster_path'] if 'poster_path' in movie and movie['poster_path'] is not None else ""
     10         return poster_url

~/miniconda3/lib/python3.6/site-packages/tmdbsimple/movies.py in info(self, **kwargs)
     61         path = self._get_id_path('info')
     62 
---> 63         response = self._GET(path, kwargs)
     64         self._set_attrs_to_values(response)
     65         return response

~/miniconda3/lib/python3.6/site-packages/tmdbsimple/base.py in _GET(self, path, params)
     83 
     84     def _GET(self, path, params=None):
---> 85         return self._request('GET', path, params=params)
     86 
     87     def _POST(self, path, params=None, payload=None):

~/miniconda3/lib/python3.6/site-packages/tmdbsimple/base.py in _request(self, method, path, params, payload)
     71     def _request(self, method, path, params=None, payload=None):
     72         url = self._get_complete_url(path)
---> 73         params = self._get_params(params)
     74 
     75         response = requests.request(

~/miniconda3/lib/python3.6/site-packages/tmdbsimple/base.py in _get_params(self, params)
     60         from . import API_KEY
     61         if not API_KEY:
---> 62             raise APIKeyError
     63 
     64         api_dict = {'api_key': API_KEY}

APIKeyError: 
```

However if I do run the poster test cell I then get:
```
HTTPError: 401 Client Error: Unauthorized for url: https://api.themoviedb.org/3/movie/1893?api_key=YOUR_API_KEY
```


What Python version are you using?
