### ISSUE TITLE
'Recommedation' errors

### ISSUE THREAD

**Issue by rhagarty** [IBM/elasticsearch-spark-recommender#16]
@MLnick - I grabbed the latest, and I'm still having issues with this.

Again, I did NOT install 'tmdbsimple' and skipped the 'optional' step of connecting to the TMDB API. Then when I get to the 'recommendation' steps, they all give me the same error:

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-48-63590843c57d> in <module>()
----> 1 display_similar(1, num=5, q="genres:children")

<ipython-input-45-0d64c89fb4d2> in display_similar(the_id, q, num, index, dt)
    144     """
    145     movie, recs = get_similar(the_id, q, num, index, dt)
--> 146     q_im_url = get_poster_url(movie['tmdbId'])
    147     if q_im_url == "NA":
    148         display(HTML("<i>Cannot import tmdbsimple. No movie posters will be displayed!</i>"))

<ipython-input-45-0d64c89fb4d2> in get_poster_url(id)
     10         poster_url = IMAGE_URL + movie['poster_path'] if 'poster_path' in movie and movie['poster_path'] is not None else ""
     11         return poster_url
---> 12     except APIKeyError as ae:
     13         return "KEY_ERR"
     14     except ModuleNotFoundError as me:

UnboundLocalError: local variable 'APIKeyError' referenced before assignment

Maybe we should make this a MANDATORY step and force the user to figure out how to correctly install tmdbsimple?

**Comment by MLnick** [comment]
Ah ok. I see the issue and will push a fix for it
