### ISSUE TITLE
Elasticsearch connector confusion

### ISSUE THREAD

**Issue by rhagarty** [IBM/elasticsearch-spark-recommender#2]
@MLnick - step 3 is confusing. The title and text calls it "elasticsearch-spark", but the downloaded file and unzip command use "elasticsearch-hadoop". Can you clarify this step?

**Comment by MLnick** [comment]
Right, good point. The `elasticsearch-hadoop` project is an umbrella for all the Hadoop ecosystem connectors, and includes specific connectors for Hadoop and Spark. `elasticsearch-spark` is the Spark-specific submodule. 

I will clarify the instructions

**Comment by MLnick** [comment]
@rhagarty I updated the docs in b2a5ec8 - let me know if is ok for you?

**Comment by rhagarty** [comment]
@MLnick - looks good. In the future, can you please submit all changes as a pull request? It makes it much easier to track and to review changes.

**Comment by MLnick** [comment]
Sure thing!
