### ISSUE TITLE
Running into build issue

### ISSUE THREAD

**Issue by rhagarty** [IBM/elasticsearch-spark-recommender#3]
@MLnick - Seeing the following error:

$ PYSPARK_DRIVER_PYTHON="jupyter" PYSPARK_DRIVER_PYTHON_OPTS="notebook" ../../spark-2.2.0-bin-hadoop2.7/bin/pyspark --driver-memory 4g --driver-class-path ../../elasticsearch-hadoop-5.3.0//dist/elasticsearch-spark_2.11-5.3.0.jar
env: jupyter: No such file or directory

**Comment by MLnick** [comment]
Is `jupyter` installed?

Also, which directory are you running the command from?

**Comment by MLnick** [comment]
Does this work:

```PYSPARK_DRIVER_PYTHON="jupyter" PYSPARK_DRIVER_PYTHON_OPTS="notebook" ../spark-2.2.0-bin-hadoop2.7/bin/pyspark --driver-memory 4g --driver-class-path ../../elasticsearch-hadoop-5.3.0/dist/elasticsearch-spark-20_2.11-5.3.0.jar```

Should be run from the Journey base directory (and assuming that Spark and `elasticsearch-hadoop` were unzipped from the parent directory of that).

**Comment by rhagarty** [comment]
@MLnick - the problem was jupyter not being installed. We need to add that to the README somewhere. Also, my notebook is using python 2.7. Is this sufficient, or should I be using 3.X? We should probably specify.

**Comment by MLnick** [comment]
Ah - yes good point, that needs to be added to the README for sure.

I will double check the Python versions but everything _should_ work for both 2.7 and 3. Will document accordingly.
