### ISSUE TITLE
name 'spark' is not defined

### ISSUE THREAD

**Issue by aclowkey** [IBM/elasticsearch-spark-recommender#34]
Downloaded and installed everything. When I'm running the `# check PySpark is running
spark` command. I get this:

> NameError                                 Traceback (most recent call last)
> <ipython-input-2-456c22950c2a> in <module>()
>       2 from IPython.display import Image, HTML, display
>       3 # check PySpark is running
> ----> 4 spark
> 
> NameError: name 'spark' is not defined

My commands:
```
SET PYSPARK_DRIVER_PYTHON=C:\Program Files (x86)\Python36-32\Scripts\jupyter.exe
SET PYSPARK_DRIVER_PYTHON_OPTS=notebook --no-browser
..\spark-2.2.0-bin-hadoop2.7\bin\pyspark --driver-memory 4g --driver-class-path ..\elasticsearch-hadoop-5.3.0\dist\elasticsearch-hadoop-5.3.0.jar
```

**Comment by MLnick** [comment]
Hi there - I'm afraid I don't have any experience with launching PySpark on Windows. Are you able to launch PySpark with juptyter console?

**Comment by MLnick** [comment]
Have you tried `pyspark.cmd` instead of `pyspark`?
