### ISSUE TITLE
PYSPARK_DRIVER_PYTHON is not defined 

### ISSUE THREAD

**Issue by RENEEGAILP** [IBM/elasticsearch-spark-recommender#36]
`PYSPARK_DRIVER_PYTHON="jupyter"`` PYSPARK_DRIVER_PYTHON_OPTS="notebook" ../spark-2.2.0-bin-hadoop2.7/bin/pyspark --driver-memory 4g --driver-class-path ../../elasticsearch-hadoop-5.3.0/dist/elasticsearch-spark-20_2.11-5.3.0.jar`
 
This gives an error in command prompt 

> PYSPARK_DRIVER_PYTHON is not recognized as an internal or external command, operable command or a batch file

**Comment by MLnick** [comment]
Which platform are you running on ?

**Comment by MLnick** [comment]
You should be able to user `--driver-class-path` but ensure you set the path to the fully qualified path name for the location where you unzipped the `elasticsearch-hadoop` JAR.

**Comment by RENEEGAILP** [comment]
![capture2](https://user-images.githubusercontent.com/22723224/37760737-737ad46c-2daf-11e8-8713-79981aaeab8e.PNG)

After opening the ipnyb in jupyter this is the error

**Comment by MLnick** [comment]
Can you try running the Windows .cmd version of pyspark :`../spark-2.2.0-bin-hadoop2.7/bin/pyspark.cmd`?

**Comment by yangjax** [comment]
> ![capture2](https://user-images.githubusercontent.com/22723224/37760737-737ad46c-2daf-11e8-8713-79981aaeab8e.PNG)
> 
> After opening the ipnyb in jupyter this is the error

i meet the same error, haver you solve it?
