### ISSUE TITLE
Location of ml-latest-small folder

### ISSUE THREAD

**Issue by rhagarty** [IBM/elasticsearch-spark-recommender#5]
In your command to unzip this file, you should mention where it should reside. I would recommend:

cd <repo-dir>/notebooks
unzip ml-latest-small.zip

This way, in step [3] of the notebook, the user can simply put:
PATH_TO_DATA = "ml-latest-small"
OR, better yet, you can make this the default so the user doesn't need to modify this cell.

I unzipped to <repo-dir>, which caused me to some pain trying to figure out what to set the PATH_TO_DATA path to be. Once I figured out that the base directory was <repo-dir>/notebooks, I set my path to "../ml-latest-small".

**Comment by MLnick** [comment]
How about `$ unzip ml-latest-small.zip -d elasticsearch-spark-recommender/notebooks/`?
