### ISSUE TITLE
Support Elasticsearch 7.x

### ISSUE THREAD

**Issue by Minx-SigEp** [IBM/elasticsearch-spark-recommender#53]
I too would be interested in seeing this repository updated to a later version of elasticsearch. With the removal of types from indexes, the introduction of the [dense_vector data type](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/dense-vector.html), and the [vector scoring plugin](https://github.com/MLnick/elasticsearch-vector-scoring) being incompatible with ES 7.x this sample could benefit from an update. There is a lot of extremely valuable information available here that is hard to apply to a current version of Elasticsearch.

**Comment by MLnick** [comment]
Agree very interesting. I will take a look - see https://github.com/IBM/elasticsearch-spark-recommender/issues/48#issuecomment-584591805

**Comment by MLnick** [comment]
See #54

**Comment by MLnick** [comment]
#54 merged
