### ISSUE TITLE
Elasticsearch error

### ISSUE THREAD

**Issue by rhagarty** [IBM/elasticsearch-spark-recommender#6]
@MLnick - getting this error in Step 2: Load data into Elasticsearch -

ImportError                               Traceback (most recent call last)
<ipython-input-11-155ac80ef9a6> in <module>()
----> 1 from elasticsearch import Elasticsearch
      2 
      3 # test your ES instance is running
      4 es = Elasticsearch()
      5 es.info(pretty=True)

ImportError: No module named elasticsearch

The work-around for me (running on Mac) was to:
export PYTHONPATH=/Library/Python/2.7/site-packages

Not sure if there is a better solution. Maybe we can add this to trouble-shooting as a "possible" solution?

**Comment by MLnick** [comment]
Hmm, perhaps we can add to troubleshooting. I haven't ever needed to update my `PYTHONPATH` in this way.

**Comment by MLnick** [comment]
Also are you running in a `conda` env? Or a `virtualenv`? Or just plain (no env)?
